### ISSUE TITLE
Fails to prompt

### ISSUE THREAD

**Issue by LuisBorromeo** [markalfred/robinhood-to-csv#21]
Luiss-MacBook-Air:robinhoodExport luisborromeo$ sudo npm install -g robinhood-to-csv
Password:
/usr/local/bin/robinhood-to-csv -> /usr/local/lib/node_modules/robinhood-to-csv/bin/robinhood-to-csv.js
/usr/local/lib
└── robinhood-to-csv@1.0.4 

Luiss-MacBook-Air:robinhoodExport luisborromeo$ robinhood-to-csv -v
/usr/local/lib/node_modules/robinhood-to-csv/bin/robinhood-to-csv.js:15
const { username, password, output } = program
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by markalfred** [comment]
@LuisBorromeo upgrading to node version 6 or greater should resolve this issue.

I created #22 to track progress on making the library compatible with older Node versions.
